"""Add anti_spam and sdg_goal

Revision ID: 4924861ed48c
Revises: ee1d3da51d16
Create Date: 2026-05-30 11:12:14.787167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4924861ed48c'
down_revision: Union[str, None] = 'ee1d3da51d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('image_hash', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('receipt_id', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('sdg_goal', sa.String(), nullable=True))
    op.create_index(op.f('ix_activities_receipt_id'), 'activities', ['receipt_id'], unique=False)
    op.create_unique_constraint(None, 'activities', ['image_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='unique')
    op.drop_index(op.f('ix_activities_receipt_id'), table_name='activities')
    op.drop_column('activities', 'sdg_goal')
    op.drop_column('activities', 'receipt_id')
    op.drop_column('activities', 'image_hash')
    # ### end Alembic commands ###
